import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:news_app/core/resources/colors_manager.dart';
import 'package:news_app/features/home/sources/article_item.dart';
import 'package:news_app/models/article_model.dart';
import 'package:news_app/models/source_model.dart';

class SourcesView extends StatelessWidget {
  SourcesView({super.key});
  List<SourceModel> sources = [
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
    SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
  ];

  List<ArticleModel> articles = [
    ArticleModel(
        source: SourceModel(
        id:"abc-news",
        name: "ABC News",
        description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
        url: "https://abcnews.go.com",
        category: "general",
        language: "en",
        country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
    ArticleModel(
        source: SourceModel(
            id:"abc-news",
            name: "ABC News",
            description: "Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.",
            url: "https://abcnews.go.com",
            category: "general",
            language: "en",
            country: "us"),
        author: "Rhett Jones",
        title: "New Bitcoin Protocol Makes Payments Easier",
        description: "Bitcoin is getting some Ethereum-like features.",
        url: "https://gizmodo.com/new-bitcoin-protocol-makes-payments-easier-2000675741",
        urlToImage: "https://gizmodo.com/app/uploads/2024/04/0ddbd47a359dbefbb14c16d0ffe99a95.jpg",
        publishedAt: "2025-10-22T20:44:30Z",
        content: "On Tuesday, Ark Labs announced the public beta launch of the highly anticipated (at least among Bitcoin purists) Arkade, which is a new upper-layer network protocol built on top of the base Bitcoin b… [+5273 chars]"),
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        DefaultTabController(
          length: sources.length,
            child: TabBar(
              tabAlignment: TabAlignment.start,
              dividerColor: Colors.transparent,
              indicatorColor: ColorsManager.white,
              labelStyle: GoogleFonts.inter(fontSize: 16.sp,fontWeight: FontWeight.bold,color: ColorsManager.white),
              unselectedLabelStyle: GoogleFonts.inter(fontSize: 14.sp,fontWeight: FontWeight.w500,color: ColorsManager.white),
              isScrollable: true,
                tabs: sources.map((source) => Tab(text: source.name,)).toList())),
        Expanded(child: ListView.separated(
          padding: REdgeInsets.symmetric(horizontal: 8,vertical: 16),
            itemBuilder: (context,index) => ArticleItem(article: articles[index],),
            separatorBuilder: (context,index) => SizedBox(height: 16.h,),
            itemCount: articles.length)
        )
      ],
    );
  }
}
